[package]
name = "openFi"
description = "A TON blockchain project"
version = "0.1.0"
license = "MIT"

[toolchain]
acton = "1.1.0"

[contracts.dao]
display-name = "DAO"
src = "phosphate/contracts/dao/dao.tolk"
depends = ["fossFi"]

[contracts.fossFi]
display-name = "FossFi"
src = "phosphate/contracts/fossFi/fossFi.tolk"
depends = ["fossFiWallet"]

[contracts.fossFiWallet]
display-name = "FossFiWallet"
src = "phosphate/contracts/fossFi/fossFiWallet.tolk"

[fmt]
width = 100
ignore = []

[import-mappings]
acton = ".acton"
contracts = "phosphate/contracts"
gen = "gen"
tests = "tests"
wrappers = "wrappers"
wrappers-ts = "wrappers-ts"
